define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid;
    var o={};
    var colors = ['#2ec7c9','#b6a2de','#5ab1ef','#ffb980','#d87a80',,'#2ec7c9','#dc69aa','#97b552','#95706d','#dc69aa'];
    
    o.init = function(domid,data){
        var cityMap = dict.get_map('city');
        gridid = domid;

        store = new mwt.Store({
            proxy: new mwt.MemoryProxy({
                data: data
            })
        });        

        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : false,     //!< 分页
            pageSize    : 100,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : false,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            filename    : '车胜总分公司车辆统计',
            emptyMsg    : '空空如也~',
            bodyStyle   : '', 
            cm: new MWT.Grid.ColumnModel([
                {head:'物料ID',dataIndex:'productId',align:'left',width:100,sort:true,render:function(v,item){
                    return v;
                }},
                {head:'品牌车型车款',dataIndex:'productName',align:'left',sort:true,render:function(v,item){
                    return cityMap[v] ? cityMap[v] : v;
                }},
                {head:'厂商指导价',dataIndex:'msrp',width:120,align:'right',sort:true,render:function(v,item){
                    return formatAmount(v);
                }},
                {head:'采购单价',dataIndex:'amount',width:120,align:'right',sort:true,render:function(v,item){
                    return formatAmount(v);
                }},
                {head:'采购数量',dataIndex:'quantity',width:100,align:'right',sort:true,render:function(v,item){
                    return number_format(v,0);
                }},
                {head:'总价',dataIndex:'amount',width:150,align:'right',sort:false,render:function(v,item){
                    var p = item.amount * item.quantity;
                    return formatAmount(p);
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 启用开关
            jQuery('[name=adenable]').unbind('change').change(function(){
                var id = jQuery(this).data('dtname');
                var enable = jQuery(this).is(':checked') ? 1 : 0;
                ajax.post('t_chesheng_plan&action=setEnable',{id:id,enabled:enable},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                    mwt.notify('已保存',1500,'success');
                });
            });
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
//            key: mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('t_t_chesheng_plan&action=remove',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
