define(function(require){
    /* generated by mengma @2019-06-18 09:15 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,callback;
    
    function init_dialog() 
    {/*{{{*/
        //1. new form
        form = new MWT.Form();
        form.addField('name',new MWT.TextField({
            type        : 'text',
            render      : 'fm-name'+dialogid,
            value       : '', 
            empty       : false,
            errmsg      : "请输入环境名称(如:prod,test,dev),不超过100个字符",
            checkfun    : function(v){return v.length<=100;}
        }));
        form.addField('url',new MWT.TextField({
            type        : 'text',
            render      : 'fm-url'+dialogid,
            value       : '', 
            empty       : false,
            errmsg      : "请输入服务URL,不超过1024个字符",
            checkfun    : function(v){return v.length<=1024;}
        }));
        //2. new dialog
        dialog = new MWT.Dialog({
            title     : '对话框',
            form      : form,
			width     : 600,
            style     : 'height:130px;',
            bodyStyle : 'padding:10px;',
            body : '<table class="mwt-formtab">'+
               '<tr>'+
                 '<td width="90">环境名称<b style="color:red">*</b></td>'+
                 '<td><div id="fm-name'+dialogid+'"></div></td>'+
                 '<td width="280" class="tips">生产环境请填"prod"</td>'+
               '</tr>'+
               '<tr>'+
                 '<td>服务URL <b style="color:red">*</b></td>'+
                 '<td colspan="2"><div id="fm-url'+dialogid+'"></div></td>'+
               '</tr>'+
            '</table>',
            buttons : [
                {label:"确定",cls:'mwt-btn-primary',handler:submitClick},
                {label:"取消",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
            form.reset();
            if (params.id) {
                dialog.setTitle("编辑后端服务环境");
                form.set(params);
				jQuery('#fm-name'+dialogid+'txt').attr('disabled','disabled').css({"background":"#eee"});
            } else {
                dialog.setTitle("添加后端服务环境");
				jQuery('#fm-name'+dialogid+'txt').removeAttr("disabled").css({"background":"#fff"});
            }
        });
    }/*}}}*/

    var o={};
    o.open=function(_params,_callback){
        params   = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    /////////////////////////////////////
    // 提交按钮点击事件
    function submitClick() {
        var data = form.getData();
        try {
            data.id = params.id;
			data.app_id = params.app_id;
            ajax.post('gwappEnv&action=save',data,function(res){
                if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
                else {
                    dialog.close();
                    if (callback) callback();
                }   
            }); 
        } catch (e) {
            mwt.notify(e,1500,'danger');
        }
    }

    return o;
});
