define(function(require){
    /* generated by mengma @2018-04-01 00:57 */
    var store,grid,gridid,appInfo;
    var dialog = require('./dialog');
    var o={};
    
    o.init = function(domid,_appInfo){
        gridid = domid;
		appInfo = _appInfo;
		var stateOpts = dict.get_options('status',{text:'全部',value:-1});
        store = new mwt.Store({
            proxy: new mwt.HttpProxy({
                //beforeLoad : store_before_load,
                //afterLoad  : store_after_load,
                url : ajax.getAjaxUrl("gwapi&action=query")
            })
        });
        grid = new MWT.Grid({
            render      : gridid,
            store       : store,
            pagebar     : true,     //!< 分页
            pageSize    : 20,       //!< 每页大小
            multiSelect : false,    //!< 多行选择
            bordered    : false,    //!< 单元格边框
            striped     : true,     //!< 斑马纹
            noheader    : false,    //!< 隐藏列头
            notoolbox   : false,    //!< 隐藏工具箱(刷新,斑马纹,导出Excel)
            position    : 'fixed',  //!< 位置(relative:相对位置,其他:固定头部和尾部)
            bodyStyle   : 'top:85px;', 
            tbarStyle   : 'margin-bottom:10px;',
            tbar: [
                {type:'select',id:'state-sel-'+gridid,label:'状态',options:stateOpts,value:-1,handler:o.query},
                {type:'search',id:'so-key-'+gridid,width:300,handler:o.query,placeholder:'搜索关键词'},
                '->',
                {label:iconlabel.plus('添加API'),handler:function(){
                    dialog.open({id:0,app_id:appInfo.id},o.query);
                }}
            ],
            cm: new MWT.Grid.ColumnModel([
                {head:'状态',dataIndex:'status',width:70,align:'left',sort:true,render:function(v,item){
                    return gridRender.state(v,'status');
                }},
                {head:'网关接口',dataIndex:'front_path',align:'left',sort:true,render:function(v,item){
					var url = setting.gateway_url+appInfo.prepath+v;
                    return '<a href="'+url+'" class="grida" '+
							  'style="font-family:monospace;color:#f57c00;" target="_blank">'+v+'</a>';
                }},
                {head:'后端服务地址',dataIndex:'back_path',width:100,align:'center',sort:false,render:function(v,item){
                    return '<a name="backbtn-'+gridid+'" data-id="'+item.id+'" '+
							  'class="mwt-btn mwt-btn-primary mwt-btn-sm radius">详情</a>';
                }},
                {head:'超时时间(毫秒)',dataIndex:'timeout',width:110,align:'right',sort:true,render:function(v,item){
                    return v;
                }},
                {head:'限流阈值',dataIndex:'max_flow',width:80,align:'right',sort:true,render:function(v,item){
                    return v;
                }},
                {head:'鉴权策略',dataIndex:'authkeys',width:120,align:'left',sort:false,render:function(v,item){
                    return v=='' ? '<span style="color:gray">无</span>' : v;
                }},
                {head:'是否mock',dataIndex:'is_mock',width:90,align:'center',sort:false,render:function(v,item){
					if (v==1) return '<span style="color:red">是</span>';
					else return '<span style="color:gray">否</span>';
                }},
                {head:'mock内容',dataIndex:'mock',width:150,align:'left',sort:false,render:function(v,item){
					if (v=='') return v;
                    return '<button class="blockbtn mwt-btn mwt-btn-default mwt-btn-sm radius" name="mockbtn-'+gridid+'" '+
							'data-id="'+item.id+'">'+v+'</button>';
                }},
                {head:'接口说明',dataIndex:'remark',width:130,align:'left',sort:false,render:function(v,item){
                    return v;
                }},
                {head:'创建日期',dataIndex:'ctime',width:120,align:'center',sort:true,render:function(v,item){
                    return '<span style="color:#aaa">'+v.substr(0,16)+'</span>';
                }},
                {head:'操作',dataIndex:'id',align:'right',width:150,sort:false,render:function(v,item){
					var disabled = item.uid==dz.uid ? '' : 'disabled';
					var cls = 'mwt-btn mwt-btn-default mwt-btn-sm';
					var pub = item.status==0 ? '上线' : '下线';
					var pubbtn = '<button class="'+cls+'" '+disabled+' name="pubbtn-'+gridid+'" data-id="'+v+'">'+pub+'</button>';
					var editbtn = '<button class="'+cls+'" '+disabled+' name="editbtn-'+gridid+'" data-id="'+v+'">修改</button>';
					var delbtn = '<button class="'+cls+'" '+disabled+' name="delbtn-'+gridid+'" data-id="'+v+'">删除</button>';
                    var btns = [pubbtn,editbtn,delbtn];
                    return '<div class="mwt-btn-group-radius">'+btns.join('')+'</div>';
                }}
            ])
        });
        store.on('load',function(){
            mwt.popinit();
			// 后端服务地址
			jQuery('[name=backbtn-'+gridid+']').unbind('click').click(function(){
                var id = jQuery(this).data('id');
				var rd = grid.getRecord('id',id);
				require('./env_dialog').open(rd,appInfo,o.query);
			});
            // 编辑按钮
            jQuery('[name=editbtn-'+gridid+']').unbind('click').click(editbtnClick);
            // 删除按钮
            jQuery('[name=delbtn-'+gridid+']').unbind('click').click(delbtnClick);
            // 上下线按钮
            jQuery('[name=pubbtn-'+gridid+']').unbind('click').click(function(){
                var id = jQuery(this).data('id');
				var rd = grid.getRecord('id',id);
				var state = rd.status==0 ? 1 : 0;
                ajax.post('gwapi&action=setStatus',{id:id,status:state},function(res){
                    if (res.retcode!=0) mwt.notify(res.retmsg,1500,'danger');
					store.load();
                });
            });
			// mock按钮
			jQuery('[name=mockbtn-'+gridid+']').unbind('click').click(function(){
				var id = jQuery(this).data('id');
				var rd = grid.getRecord('id',id);
				require('./mock_dialog').open(rd);
			});
        });
        grid.create();
        o.query();
    };

    // 查询
    o.query = function() {
        store.baseParams = {
            state: mwt.get_select_value('state-sel-'+gridid),
			app_id: appInfo.id,
            key: mwt.get_value("so-key-"+gridid)
        };
        grid.load();
    };

    // 编辑按钮点击事件
    function editbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        var item = grid.getRecord('id',id);
        dialog.open(item,o.query);
    }/*}}}*/

    // 删除按钮点击事件
    function delbtnClick() 
    {/*{{{*/
        var id = jQuery(this).data('id');
        mwt.confirm('确定要删除吗?',function(res){
            if (!res) return;
            ajax.post('t_api&action=remove',{id:id},function(res){
                if (res.retcode!=0) mwt.alert(res.retmsg);
                else {
                    o.query();
                }
            });
        });
    }/*}}}*/

    return o;
});
