define(function(require){
    /* generated by mengma @2019-06-18 10:43 */
    var dialogid = 'dialog-'+mwt.genId();
    var form,dialog,params,appInfo,callback;
    
    function init_dialog() 
    {
        dialog = new MWT.Dialog({
            title     : 'Mock内容',
            form      : form,
			width     : 600,
			style     : 'height:500px;',
            bodyStyle : 'padding:10px;',
            body : '<div class="mwt-layout-fill" id="main-'+dialogid+'" style="word-break:break-all;padding:20px;font-size:13px;"></div>',
            buttons : [
                {label:"关闭",type:'close',cls:'mwt-btn-default'}
            ]
        });
        //3. dialog open event
        dialog.on('open',function(){
			jQuery('#main-'+dialogid).html(params.mock);
        });
    }

    var o={};
    o.open=function(_params,_callback){
        params  = _params;
        callback = _callback;
        if (!dialog) init_dialog();
        dialog.open();
    };  

    return o;
});
